JIT: Fixes signed displacement wraparound on 32-bit
FEX-Emu/FEX pull request #1518
Opened 2022-01-14 09:49 UTC by Sonicadvance1

This cropped up mostly with multiblock and `jmp <signed displacement>`
This also happened with non multiblock `jcc <signed displacement>`

Due to how IR relocations occur, this needs to happen fairly late but
isn't a big deal.

Fixes #1517

2022-01-14 13:39 UTC, skmp requested changes
The x86/64 check should be moved to the frontend, as we don't want configuration state to affect the backends, so they can be used in an offline way, and IR files should contain all information to emit the code.

I'd opt in to move it as a parameter (32bitwrap or something), so what happens is clearly defined.

2022-01-15 00:34 UTC, Sonicadvance1 commented
This has been moved to the opcode dispatcher. I also fixed and implemented unit tests for overflow on RIP as well as the underflow tests.

2022-01-15 05:25 UTC, Sonicadvance1 commented
Side note, this PR fixes Counter-Strike: Condition Zero.

2022-01-19 15:06 UTC, skmp commented
Still thinking of this, as it doesn't handle the relocation case.

2022-01-19 17:48 UTC, Sonicadvance1 commented
I don't think that should be a blocker to this change.
Even without this change relocations could still have issues.

2022-01-20 20:33 UTC, skmp commented
Carved a bit more time today to think on this a bit more, the unwrapping logic really unnerves me.

My view is that
- The opdispatch handlers should only do the 32 bit masking themselves
- `GetDynamicPC` should be extended with an "is32bit" parameter, and do the masking there too, in the offset calculations
- The IR/Backed (EntrypointOffset/InlineEntrypointOffset) should be extended to correctly do 32-bit or 64-bit operation
- While we're at it, possibly rename `GetDynamicPC` to `GetRelocatedPC` for clarity

This will simplify the semantics of the code, force us to specify 32 or 64 bit usage in GetDynamicPC everywhere (and hopefully make sure no other similar bugs exist) and also handle relocations

2022-01-24 02:56 UTC, Sonicadvance1 commented
PR updated to address comments.

2022-01-25 18:29 UTC, merged