SMC: Guarantee that stale code is not compiled
FEX-Emu/FEX pull request #1766
Opened 2022-06-10 07:02 UTC by skmp

2022-06-10 07:12 UTC, skmp commented
Funny how the test always passes for x86 hosts. Hmm.

2022-06-10 13:04 UTC, neobrain requested changes
Couple of minor things that need a quick pass, looks fine otherwise!

2022-06-11 09:50 UTC, skmp commented on External/FEXCore/Source/Interface/Core/LookupCache.h
>      for (auto CurrentPage = Start >> 12, EndPage = (Start + Length) >> 12; CurrentPage <= EndPage; CurrentPage++) {
Possibly, I think we are "over including" blocks in a few other spots as well

2022-06-11 09:51 UTC, skmp commented on External/FEXCore/Source/Interface/Core/Frontend.cpp
> +      // This is worst case
The comment is about using `MAX_INST_SIZE`, not about the cross page tracking logic

2022-06-11 10:00 UTC, skmp commented on External/FEXCore/Source/Interface/Core/LookupCache.h
> +  // Appends Block {Address} to the blocks contained between [Start, Start + Length)
`FindBlock` actually lookups mappings, not block, though

2022-06-11 12:49 UTC, skmp commented
Spurious fail of `FEXLT:pthread_cancel` logged in #1754

2022-06-11 13:05 UTC, merged

2022-06-11 13:05 UTC, skmp commented
(force merged this as it was blocking other work)