Removes GDBSymbol integration
FEX-Emu/FEX pull request #3969
Opened 2024-08-17 02:46 UTC by Sonicadvance1

This was only ever wired up to the AOT interface, so was mostly broken.

I've never used this, it's integration wasn't ever fully fleshed out, just get rid of it.

2024-08-17 12:28 UTC, alyssarosenzweig approved these changes

2024-08-17 12:44 UTC, Conan-Kudo approved these changes

2024-08-19 09:14 UTC, neobrain requested changes
This gets a -1 from me. Our debugging infrastructure has been continuously regressing (complete breakage of the already limited GDB stub (#3431), removal of interpreter (#3128), removal of x86 support (#3134), ...). Meanwhile, improvements that could balance this out have been progressing slowly or stalled entirely.

The GDB JIT integration is one of the few remaining tools we have to debug complex guest code, so I'd rather keep it until our debugging story meaningfully improves.

2024-08-19 09:19 UTC, neobrain commented
> This was only ever wired up to the AOT interface, so was mostly broken.

The feature was working fine in the past, has anything changed? Off the top of my head, I think the GDB JIT integration code just generates source map files whenever the guest loads libraries (using the same interfaces as AOT uses), but it shouldn't be a no-op unless we broke something recently.

2024-08-19 17:56 UTC, closed without merging